// <auto-generated />
using System;
using ExcellCore.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcellCore.Domain.Data.Migrations
{
    [DbContext(typeof(ExcellCoreContext))]
    [Migration("20251227140000_RetailAndCorporateDashboards")]
    partial class RetailAndCorporateDashboards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ExcellCore.Domain.Entities.ActionLog", b =>
                {
                    b.Property<Guid>("ActionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgreementApprovalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ActionLogId");

                    b.HasIndex("AgreementApprovalId");

                    b.HasIndex("AgreementId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.Property<Guid>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgreementName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastRenewedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Draft");

                    b.HasKey("AgreementId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementApproval", b =>
                {
                    b.Property<Guid>("AgreementApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EscalatedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementApprovalId");

                    b.HasIndex("AgreementId");

                    b.ToTable("AgreementApprovals");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementImpactedParty", b =>
                {
                    b.Property<Guid>("AgreementImpactedPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementImpactedPartyId");

                    b.HasIndex("PartyId");

                    b.HasIndex("AgreementId", "PartyId")
                        .IsUnique();

                    b.ToTable("AgreementImpactedParties");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementRate", b =>
                {
                    b.Property<Guid>("AgreementRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CopayPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementRateId");

                    b.HasIndex("AgreementId");

                    b.ToTable("AgreementRates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.CorporateContract", b =>
                {
                    b.Property<Guid>("CorporateContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationRatio")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CorporateContractId");

                    b.ToTable("CorporateContracts");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyIdentifier", b =>
                {
                    b.Property<Guid>("PartyIdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyIdentifierId");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyIdentifiers");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailTransaction", b =>
                {
                    b.Property<Guid>("RetailTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LoyaltyEnrollment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RetailTransactionId");

                    b.ToTable("RetailTransactions");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryEvent", b =>
                {
                    b.Property<Guid>("TelemetryEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("TelemetryEventId");

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaisedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RetailTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.HasIndex("RetailTransactionId", "TicketNumber");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.ActionLog", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.AgreementApproval", null)
                        .WithMany()
                        .HasForeignKey("AgreementApprovalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany()
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ActionLogId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("ActionLogId");

                            b1.ToTable("ActionLogs");

                            b1.WithOwner()
                                .HasForeignKey("ActionLogId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementId");

                            b1.ToTable("Agreements");

                            b1.WithOwner()
                                .HasForeignKey("AgreementId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementApproval", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("Approvals")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementApprovalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementApprovalId");

                            b1.ToTable("AgreementApprovals");

                            b1.WithOwner()
                                .HasForeignKey("AgreementApprovalId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementImpactedParty", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("ImpactedParties")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExcellCore.Domain.Entities.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementImpactedPartyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementImpactedPartyId");

                            b1.ToTable("AgreementImpactedParties");

                            b1.WithOwner()
                                .HasForeignKey("AgreementImpactedPartyId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementRate", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("Rates")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementRateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementRateId");

                            b1.ToTable("AgreementRates");

                            b1.WithOwner()
                                .HasForeignKey("AgreementRateId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.CorporateContract", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CorporateContractId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("CorporateContractId");

                            b1.ToTable("CorporateContracts");

                            b1.WithOwner()
                                .HasForeignKey("CorporateContractId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyIdentifier", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Party", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartyIdentifierId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("PartyIdentifierId");

                            b1.ToTable("PartyIdentifiers");

                            b1.WithOwner()
                                .HasForeignKey("PartyIdentifierId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailTransaction", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RetailTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("RetailTransactionId");

                            b1.ToTable("RetailTransactions");

                            b1.WithOwner()
                                .HasForeignKey("RetailTransactionId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryEvent", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TelemetryEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("TelemetryEventId");

                            b1.ToTable("TelemetryEvents");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryEventId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.RetailTransaction", "RetailTransaction")
                        .WithMany("Tickets")
                        .HasForeignKey("RetailTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId");

                            b1.ToTable("Tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("RetailTransaction");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ImpactedParties");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailTransaction", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
