// <auto-generated />
using System;
using ExcellCore.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcellCore.Domain.Data.Migrations
{
    [DbContext(typeof(ExcellCoreContext))]
    [Migration("20251227044349_202512270515_ApprovalEscalationFlag")]
    partial class _202512270515_ApprovalEscalationFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.Property<Guid>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgreementName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastRenewedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Draft");

                    b.HasKey("AgreementId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementApproval", b =>
                {
                    b.Property<Guid>("AgreementApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EscalatedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementApprovalId");

                    b.HasIndex("AgreementId");

                    b.ToTable("AgreementApprovals");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementRate", b =>
                {
                    b.Property<Guid>("AgreementRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CopayPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementRateId");

                    b.HasIndex("AgreementId");

                    b.ToTable("AgreementRates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyIdentifier", b =>
                {
                    b.Property<Guid>("PartyIdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyIdentifierId");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyIdentifiers");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementId");

                            b1.ToTable("Agreements");

                            b1.WithOwner()
                                .HasForeignKey("AgreementId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementApproval", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("Approvals")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementApprovalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementApprovalId");

                            b1.ToTable("AgreementApprovals");

                            b1.WithOwner()
                                .HasForeignKey("AgreementApprovalId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementRate", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("Rates")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementRateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementRateId");

                            b1.ToTable("AgreementRates");

                            b1.WithOwner()
                                .HasForeignKey("AgreementRateId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyIdentifier", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Party", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartyIdentifierId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("PartyIdentifierId");

                            b1.ToTable("PartyIdentifiers");

                            b1.WithOwner()
                                .HasForeignKey("PartyIdentifierId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.Navigation("Identifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
