// <auto-generated />
using ExcellCore.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ExcellCore.Domain.Data.Migrations
{
    [DbContext(typeof(ExcellCoreContext))]
    [Migration("202512271530_ReportingWorkspacePersistence")]
    partial class ReportingWorkspacePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new SnapshotProxy().Invoke(modelBuilder);
        }

        private sealed class SnapshotProxy : ExcellCoreContextModelSnapshot
        {
            public void Invoke(ModelBuilder modelBuilder)
            {
                base.BuildModel(modelBuilder);
            }
        }
    }
}
