// <auto-generated />
using System;
using ExcellCore.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcellCore.Domain.Data.Migrations
{
    [DbContext(typeof(ExcellCoreContext))]
    [Migration("20260102144900_202601021530_M6ClinicalRetail")]
    partial class _202601021530_M6ClinicalRetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ExcellCore.Domain.Entities.ActionLog", b =>
                {
                    b.Property<Guid>("ActionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgreementApprovalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ActionLogId");

                    b.HasIndex("AgreementApprovalId");

                    b.HasIndex("AgreementId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.Property<Guid>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgreementName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastRenewedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Draft");

                    b.HasKey("AgreementId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementApproval", b =>
                {
                    b.Property<Guid>("AgreementApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Approver")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EscalatedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementApprovalId");

                    b.HasIndex("AgreementId");

                    b.ToTable("AgreementApprovals");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementImpactedParty", b =>
                {
                    b.Property<Guid>("AgreementImpactedPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementImpactedPartyId");

                    b.HasIndex("PartyId");

                    b.HasIndex("AgreementId", "PartyId")
                        .IsUnique();

                    b.ToTable("AgreementImpactedParties");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementRate", b =>
                {
                    b.Property<Guid>("AgreementRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CopayPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementRateId");

                    b.HasIndex("AgreementId");

                    b.ToTable("AgreementRates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.CorporateContract", b =>
                {
                    b.Property<Guid>("CorporateContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationRatio")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("AllocationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("TEXT");

                    b.HasKey("CorporateContractId");

                    b.ToTable("CorporateContracts");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.DispenseEvent", b =>
                {
                    b.Property<Guid>("DispenseEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DispensedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DispensedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryItem")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicationOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("DispenseEventId");

                    b.HasIndex("MedicationOrderId", "DispensedOnUtc");

                    b.ToTable("DispenseEvents");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.MedicationAdministration", b =>
                {
                    b.Property<Guid>("MedicationAdministrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AdministeredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicationOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledForUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("MedicationAdministrationId");

                    b.HasIndex("MedicationOrderId", "ScheduledForUtc");

                    b.ToTable("MedicationAdministrations");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.MedicationOrder", b =>
                {
                    b.Property<Guid>("MedicationOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderingProvider")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("MedicationOrderId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PartyId");

                    b.ToTable("MedicationOrders");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyIdentifier", b =>
                {
                    b.Property<Guid>("PartyIdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyIdentifierId");

                    b.HasIndex("PartyId");

                    b.ToTable("PartyIdentifiers");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyMetadata", b =>
                {
                    b.Property<Guid>("PartyMetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("PartyMetadataId");

                    b.HasIndex("PartyId", "Context", "Key")
                        .IsUnique();

                    b.ToTable("PartyMetadata");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.ReportingDashboard", b =>
                {
                    b.Property<Guid>("ReportingDashboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ReportingDashboardId");

                    b.ToTable("ReportingDashboards");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.ReportingSchedule", b =>
                {
                    b.Property<Guid>("ReportingScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Cadence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextRunUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ReportingScheduleId");

                    b.ToTable("ReportingSchedules");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailReturn", b =>
                {
                    b.Property<Guid>("RetailReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RetailTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RetailReturnId");

                    b.HasIndex("RetailTransactionId", "TicketNumber");

                    b.ToTable("RetailReturns");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailSuspendedTransaction", b =>
                {
                    b.Property<Guid>("RetailSuspendedTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResumedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SuspendedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RetailSuspendedTransactionId");

                    b.HasIndex("TicketNumber");

                    b.ToTable("RetailSuspendedTransactions");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailTransaction", b =>
                {
                    b.Property<Guid>("RetailTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LoyaltyEnrollment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RetailTransactionId");

                    b.ToTable("RetailTransactions");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.SyncChangeLedgerEntry", b =>
                {
                    b.Property<Guid>("SyncChangeLedgerEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginDeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginSiteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SyncChangeLedgerEntryId");

                    b.HasIndex("AggregateType", "AggregateId", "ObservedOnUtc");

                    b.ToTable("SyncChangeLedgerEntries");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.SyncState", b =>
                {
                    b.Property<Guid>("SyncStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VectorClockJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SyncStateId");

                    b.HasIndex("AggregateType", "AggregateId")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryAggregate", b =>
                {
                    b.Property<Guid>("TelemetryAggregateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageDurationMs")
                        .HasColumnType("REAL");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("P95DurationMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("TelemetryAggregateId");

                    b.HasIndex("MetricKey", "PeriodStartUtc");

                    b.ToTable("TelemetryAggregates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryEvent", b =>
                {
                    b.Property<Guid>("TelemetryEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("TelemetryEventId");

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryHealthSnapshot", b =>
                {
                    b.Property<Guid>("TelemetryHealthSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("P95DurationMs")
                        .HasColumnType("REAL");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("TelemetryHealthSnapshotId");

                    b.HasIndex("MetricKey", "CapturedOnUtc");

                    b.ToTable("TelemetryHealthSnapshots");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryThreshold", b =>
                {
                    b.Property<Guid>("TelemetryThresholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CriticalThresholdMs")
                        .HasColumnType("REAL");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("WarningThresholdMs")
                        .HasColumnType("REAL");

                    b.HasKey("TelemetryThresholdId");

                    b.HasIndex("MetricKey")
                        .IsUnique();

                    b.ToTable("TelemetryThresholds");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaisedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RetailTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.HasIndex("RetailTransactionId", "TicketNumber");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.ActionLog", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.AgreementApproval", null)
                        .WithMany()
                        .HasForeignKey("AgreementApprovalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany()
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ActionLogId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("ActionLogId");

                            b1.ToTable("ActionLogs");

                            b1.WithOwner()
                                .HasForeignKey("ActionLogId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementId");

                            b1.ToTable("Agreements");

                            b1.WithOwner()
                                .HasForeignKey("AgreementId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementApproval", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("Approvals")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementApprovalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementApprovalId");

                            b1.ToTable("AgreementApprovals");

                            b1.WithOwner()
                                .HasForeignKey("AgreementApprovalId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementImpactedParty", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("ImpactedParties")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExcellCore.Domain.Entities.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementImpactedPartyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementImpactedPartyId");

                            b1.ToTable("AgreementImpactedParties");

                            b1.WithOwner()
                                .HasForeignKey("AgreementImpactedPartyId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.AgreementRate", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Agreement", null)
                        .WithMany("Rates")
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("AgreementRateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("AgreementRateId");

                            b1.ToTable("AgreementRates");

                            b1.WithOwner()
                                .HasForeignKey("AgreementRateId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.CorporateContract", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CorporateContractId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("CorporateContractId");

                            b1.ToTable("CorporateContracts");

                            b1.WithOwner()
                                .HasForeignKey("CorporateContractId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.DispenseEvent", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.MedicationOrder", null)
                        .WithMany("DispenseEvents")
                        .HasForeignKey("MedicationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("DispenseEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("DispenseEventId");

                            b1.ToTable("DispenseEvents");

                            b1.WithOwner()
                                .HasForeignKey("DispenseEventId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.MedicationAdministration", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.MedicationOrder", null)
                        .WithMany("Administrations")
                        .HasForeignKey("MedicationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MedicationAdministrationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("MedicationAdministrationId");

                            b1.ToTable("MedicationAdministrations");

                            b1.WithOwner()
                                .HasForeignKey("MedicationAdministrationId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.MedicationOrder", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("MedicationOrderId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("MedicationOrderId");

                            b1.ToTable("MedicationOrders");

                            b1.WithOwner()
                                .HasForeignKey("MedicationOrderId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyIdentifier", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Party", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartyIdentifierId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("PartyIdentifierId");

                            b1.ToTable("PartyIdentifiers");

                            b1.WithOwner()
                                .HasForeignKey("PartyIdentifierId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.PartyMetadata", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("PartyMetadataId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("PartyMetadataId");

                            b1.ToTable("PartyMetadata");

                            b1.WithOwner()
                                .HasForeignKey("PartyMetadataId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.ReportingDashboard", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ReportingDashboardId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("ReportingDashboardId");

                            b1.ToTable("ReportingDashboards");

                            b1.WithOwner()
                                .HasForeignKey("ReportingDashboardId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.ReportingSchedule", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ReportingScheduleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("ReportingScheduleId");

                            b1.ToTable("ReportingSchedules");

                            b1.WithOwner()
                                .HasForeignKey("ReportingScheduleId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailReturn", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RetailReturnId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("RetailReturnId");

                            b1.ToTable("RetailReturns");

                            b1.WithOwner()
                                .HasForeignKey("RetailReturnId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailSuspendedTransaction", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RetailSuspendedTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("RetailSuspendedTransactionId");

                            b1.ToTable("RetailSuspendedTransactions");

                            b1.WithOwner()
                                .HasForeignKey("RetailSuspendedTransactionId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailTransaction", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RetailTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("RetailTransactionId");

                            b1.ToTable("RetailTransactions");

                            b1.WithOwner()
                                .HasForeignKey("RetailTransactionId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.SyncChangeLedgerEntry", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("SyncChangeLedgerEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("SyncChangeLedgerEntryId");

                            b1.ToTable("SyncChangeLedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("SyncChangeLedgerEntryId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.SyncState", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("SyncStateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("SyncStateId");

                            b1.ToTable("SyncStates");

                            b1.WithOwner()
                                .HasForeignKey("SyncStateId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryAggregate", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TelemetryAggregateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("TelemetryAggregateId");

                            b1.ToTable("TelemetryAggregates");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryAggregateId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryEvent", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TelemetryEventId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("TelemetryEventId");

                            b1.ToTable("TelemetryEvents");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryEventId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryHealthSnapshot", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TelemetryHealthSnapshotId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("TelemetryHealthSnapshotId");

                            b1.ToTable("TelemetryHealthSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryHealthSnapshotId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.TelemetryThreshold", b =>
                {
                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TelemetryThresholdId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("TelemetryThresholdId");

                            b1.ToTable("TelemetryThresholds");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryThresholdId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("ExcellCore.Domain.Entities.RetailTransaction", "RetailTransaction")
                        .WithMany("Tickets")
                        .HasForeignKey("RetailTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ExcellCore.Domain.Entities.AuditTrail", "Audit", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceModule")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("TicketId");

                            b1.ToTable("Tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();

                    b.Navigation("RetailTransaction");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Agreement", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ImpactedParties");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.MedicationOrder", b =>
                {
                    b.Navigation("Administrations");

                    b.Navigation("DispenseEvents");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.Party", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("ExcellCore.Domain.Entities.RetailTransaction", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
